spring.application.name=backend


#url base
server.servlet.context-path=/projeto-integrador

server.port=8080

#spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_integrador
spring.datasource.url=${DB_URL}
spring.datasource.username=postgres
spring.datasource.password=2016010124
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.error.include-stacktrace=never
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

spring.devtools.restart.enabled=false


cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB





#ocpp.api.base-url=http://localhost:8090

#url do codigo python
ocpp.api.base-url=${URL_OCPP_SERVER}

#apontando pro servidor micromobilidade
#ocpp.api.base-url=https://procreate-opacity-wrist.ngrok-free.dev
#server.address=0.0.0.0

ocpp.api.secret=${OCPP_SECRET}
ocpp.api.issuer=${OCPP_ISSUER}



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


api.mercado.pago.token=${MP_TOKEN}


#rodando no meu pc com NGROK -> tirar quando for pro servidor
#o ngrok serve para pegar o que a api publica posta e transferir pro meu localhost
#mercadoPafo -> ngrok -> localhost

#ngrok http 8080 ou .\ngrok.exe http 8080
#a url muda sempre
#webhook.url=https://procreate-opacity-wrist.ngrok-free.dev/projeto-integrador/webhook
webhook.url=${WEBHOOK_URL}

