spring.application.name=backend


#url base
server.servlet.context-path=/projeto-integrador

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/projeto-integrador
spring.datasource.username=postgres
spring.datasource.password=2016010124
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.error.include-stacktrace=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

spring.devtools.restart.enabled=false



cloudinary.cloud_name=dcwcurcly
cloudinary.api_key=447918755185261
cloudinary.api_secret=C1ZR303q_qu8Q552qAB9noMr5hE





ocpp.api.base-url=http://192.168.100.73:8080